{"timestamp":"2025-05-26T04:36:03.301205","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-26T04:36:03.312405","level":"info","event":"Filling up the DagBag from /home/sheela/airflow/dags/orderinfo_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-26T04:36:06.411526Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:06.414391Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:06.414876Z","level":"info","event":"Current task name:run_kpi_analysis","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:06.415252Z","level":"info","event":"Dag name:orderinfo_etl_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.021616","level":"warning","event":"pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.","category":"UserWarning","filename":"/home/sheela/airflow/dags/kpi_analysis.py","lineno":41,"logger":"py.warnings"}
{"timestamp":"2025-05-26T04:36:07.168995","level":"warning","event":"pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.","category":"UserWarning","filename":"/home/sheela/airflow/dags/kpi_analysis.py","lineno":41,"logger":"py.warnings"}
{"timestamp":"2025-05-26T04:36:07.210293Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.210679Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.210939Z","level":"info","event":"Task:<Task(PythonOperator): run_kpi_analysis>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.211132Z","level":"info","event":"Failure caused by Execution failed on sql '","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.211309Z","level":"info","event":"            SELECT COUNT(*) AS cancelled_orders,","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.211488Z","level":"info","event":"                   ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM orderinfo_bq), 2) AS cancellation_rate_percentage","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.211682Z","level":"info","event":"            FROM orderinfo_bq WHERE is_cancelled = true;","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.211852Z","level":"info","event":"        ': division by zero","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.212023Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T04:36:07.200948","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"DatabaseError","exc_value":"Execution failed on sql '\n            SELECT COUNT(*) AS cancelled_orders,\n                   ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM orderinfo_bq), 2) AS cancellation_rate_percentage\n            FROM orderinfo_bq WHERE is_cancelled = true;\n        ': division by zero\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/sheela/airflow/dags/kpi_analysis.py","lineno":41,"name":"run_kpi_analysis"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":526,"name":"read_sql_query"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2738,"name":"read_query"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2686,"name":"execute"}]},{"exc_type":"DivisionByZero","exc_value":"division by zero\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2674,"name":"execute"}]}]}
{"timestamp":"2025-05-26T10:22:27.088549","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-26T10:22:27.097082","level":"info","event":"Filling up the DagBag from /home/sheela/airflow/dags/orderinfo_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-26T10:22:31.368939Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:31.369352Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:31.369664Z","level":"info","event":"Current task name:run_kpi_analysis","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:31.369920Z","level":"info","event":"Dag name:orderinfo_etl_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:32.034136","level":"warning","event":"pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.","category":"UserWarning","filename":"/home/sheela/airflow/dags/kpi_analysis.py","lineno":41,"logger":"py.warnings"}
{"timestamp":"2025-05-26T10:22:32.045376","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"DatabaseError","exc_value":"Execution failed on sql 'SELECT COUNT(*) AS total_orders FROM orderinfo_bq;': relation \"orderinfo_bq\" does not exist\nLINE 1: SELECT COUNT(*) AS total_orders FROM orderinfo_bq;\n                                             ^\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/sheela/airflow/dags/kpi_analysis.py","lineno":41,"name":"run_kpi_analysis"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":526,"name":"read_sql_query"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2738,"name":"read_query"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2686,"name":"execute"}]},{"exc_type":"UndefinedTable","exc_value":"relation \"orderinfo_bq\" does not exist\nLINE 1: SELECT COUNT(*) AS total_orders FROM orderinfo_bq;\n                                             ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2674,"name":"execute"}]}]}
{"timestamp":"2025-05-26T10:22:32.419693Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:32.420590Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:32.421201Z","level":"info","event":"Task:<Task(PythonOperator): run_kpi_analysis>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:32.421931Z","level":"info","event":"Failure caused by Execution failed on sql 'SELECT COUNT(*) AS total_orders FROM orderinfo_bq;': relation \"orderinfo_bq\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:32.422436Z","level":"info","event":"LINE 1: SELECT COUNT(*) AS total_orders FROM orderinfo_bq;","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:32.422738Z","level":"info","event":"                                             ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T10:22:32.423991Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:08.833182","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-26T11:02:08.836619","level":"info","event":"Filling up the DagBag from /home/sheela/airflow/dags/orderinfo_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-26T11:02:10.617031Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:10.618551Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:10.619066Z","level":"info","event":"Current task name:run_kpi_analysis","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:10.619615Z","level":"info","event":"Dag name:orderinfo_etl_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:10.864279","level":"warning","event":"pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.","category":"UserWarning","filename":"/home/sheela/airflow/dags/kpi_analysis.py","lineno":41,"logger":"py.warnings"}
{"timestamp":"2025-05-26T11:02:10.911123","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"DatabaseError","exc_value":"Execution failed on sql 'SELECT COUNT(*) AS total_orders FROM orderinfo_bq;': relation \"orderinfo_bq\" does not exist\nLINE 1: SELECT COUNT(*) AS total_orders FROM orderinfo_bq;\n                                             ^\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/sheela/airflow/dags/kpi_analysis.py","lineno":41,"name":"run_kpi_analysis"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":526,"name":"read_sql_query"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2738,"name":"read_query"},{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2686,"name":"execute"}]},{"exc_type":"UndefinedTable","exc_value":"relation \"orderinfo_bq\" does not exist\nLINE 1: SELECT COUNT(*) AS total_orders FROM orderinfo_bq;\n                                             ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/mnt/c/Users/SJENNIFE/airflow_test/lib/python3.12/site-packages/pandas/io/sql.py","lineno":2674,"name":"execute"}]}]}
{"timestamp":"2025-05-26T11:02:10.913956Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:11.164815Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:11.165149Z","level":"info","event":"Task:<Task(PythonOperator): run_kpi_analysis>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:11.165395Z","level":"info","event":"Failure caused by Execution failed on sql 'SELECT COUNT(*) AS total_orders FROM orderinfo_bq;': relation \"orderinfo_bq\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:11.165616Z","level":"info","event":"LINE 1: SELECT COUNT(*) AS total_orders FROM orderinfo_bq;","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:11.165827Z","level":"info","event":"                                             ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-26T11:02:11.166035Z","level":"info","event":"","chan":"stdout","logger":"task"}
